export const REQUEST_SIGNIN = 'REQUEST_SIGNIN';
export const REQUEST_SIGNIN_SUCCESS = 'REQUEST_SIGNIN_SUCCESS';
export const REQUEST_SIGNIN_FAILED = 'REQUEST_SIGNIN_FAILED';

export const REQUEST_GET_TRANSACTION_PERYEAR = 'REQUEST_GET_TRANSACTION_PERYEAR';
export const REQUEST_GET_TRANSACTION_PERYEAR_SUCCESS = 'REQUEST_GET_TRANSACTION_PERYEAR_SUCCESS';
export const REQUEST_GET_TRANSACTION_PERYEAR_FAILED = 'REQUEST_GET_TRANSACTION_PERYEAR_FAILED';