import {
    faBars,
    faCaretDown,
    faChevronCircleDown,
    faCheck,
    faPlusSquare,
    faEllipsisV,
    faCheckSquare,
    faPercent,
    faImage,
    faPlus,
    faMinus,
    faTimesCircle,
    faUpload,
    faImages,
    faInfoCircle,
    faHome,
    faSignal,
    faMoneyBillWaveAlt,
    faExclamationCircle,
    faSort
} from '@fortawesome/free-solid-svg-icons';
import { library } from '@fortawesome/fontawesome-svg-core';

library.add(
    faBars,
    faCaretDown,
    faChevronCircleDown,
    faCheck,
    faPlusSquare,
    faEllipsisV,
    faCheckSquare,
    faPercent,
    faImage,
    faPlus,
    faTimesCircle,
    faUpload,
    faImages,
    faInfoCircle,
    faMinus,
    faHome,
    faSignal,
    faMoneyBillWaveAlt,
    faExclamationCircle,
    faSort
);
